version: '3.9'

services:

  frontend:
    build: ./frontend
    ports:
      - '3000:5173'

  backend:
    build: ./backend
    ports:
      - '5000:5000'

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'